# Aula 01 - Dados com muitas dimensões
## Objetivo
#### Neste curso estamos trabalhando para uma start up da área da saúde, a Alura Care. Fomos contratados para desenvolver uma ferramenta que, à partir dos exames do indivíduo, possa definir se o paciente está ou não com câncer. Para isso será necessário analisar os dados dos exames e diagnósticos que já possuímos para tentar, por meio de IA, determinar a condição de pacientes futuros de forma automática. 
## Metodologia
####

In [2]:
import pandas as pd

print("Carregando a base de dados")
## Carregando a base de dados
resultados = pd.read_csv('dataset/exames.csv')
print("Dados Carregados com sucesso")
resultados.head()

         id diagnostico  exame_1  ...  exame_31  exame_32  exame_33
0    842302           M    17.99  ...    0.4601   0.11890       NaN
1    842517           M    20.57  ...    0.2750   0.08902       NaN
2  84300903           M    19.69  ...    0.3613   0.08758       NaN
3  84348301           M    11.42  ...    0.6638   0.17300       NaN
4  84358402           M    20.29  ...    0.2364   0.07678  0.854454

[5 rows x 35 columns]

## Filtragem dos valores NaN

In [8]:
# O classificador random foreste não aceita valores NaN
# 1# deve-se encontrar os valores NaN na nossa tabela

resultados.isnull()

        id  diagnostico  exame_1  ...  exame_31  exame_32  exame_33
0    False        False    False  ...     False     False      True
1    False        False    False  ...     False     False      True
2    False        False    False  ...     False     False      True
3    False        False    False  ...     False     False      True
4    False        False    False  ...     False     False     False
..     ...          ...      ...  ...       ...       ...       ...
564  False        False    False  ...     False     False     False
565  False        False    False  ...     False     False      True
566  False        False    False  ...     False     False      True
567  False        False    False  ...     False     False      True
568  False        False    False  ...     False     False      True

[569 rows x 35 columns]

In [9]:
# Para saber a quantidade de NaN que temos em cada coluna basta
# somar os 'false' e os 'true'

resultados.isnull().sum()

# Com isso, observa-se que apenas a coluna 33 possui valores NaN.

id               0
diagnostico      0
exame_1          0
exame_2          0
exame_3          0
exame_4          0
exame_5          0
exame_6          0
exame_7          0
exame_8          0
exame_9          0
exame_10         0
exame_11         0
exame_12         0
exame_13         0
exame_14         0
exame_15         0
exame_16         0
exame_17         0
exame_18         0
exame_19         0
exame_20         0
exame_21         0
exame_22         0
exame_23         0
exame_24         0
exame_25         0
exame_26         0
exame_27         0
exame_28         0
exame_29         0
exame_30         0
exame_31         0
exame_32         0
exame_33       419
dtype: int64

In [18]:
print('Como %.2f%% dos dados da coluna estão comprometidos, vale a pena removê-la como um todo'%(419/resultados.shape[0]*100))

Como 73.64% dos dados da coluna estão comprometidos, vale a pena remover ela como um todo

### Divisão em base de dados em treino e teste

In [22]:
from sklearn.model_selection import train_test_split
from numpy import random

SEED = 123143
random.seed(SEED)

valores_exames = resultados.drop(columns=['id', 'diagnostico'])
diagnostico = resultados.diagnostico

# primeiro tratamento dos dados. Retirada do exame 33
valores_exames_v1 = valores_exames.drop(columns = 'exame_33')

treino_x, teste_x, treino_y, teste_y = train_test_split(valores_exames_v1,
                                                        diagnostico, 
                                                       test_size = .3)
print("Os dados foram divididos em treino e teste, com as proporções 70%% - 30%%")

In [23]:
treino_x.head()

     exame_1  exame_2  exame_3  exame_4  ...  exame_29  exame_30  exame_31  exame_32
268    12.87    16.21    82.38   103.78  ...     0.786    0.0578    0.3604   0.07062
422    11.61    16.02    75.46   103.78  ...     0.786    0.1105    0.2787   0.07427
168    17.47    24.68   116.10   103.78  ...     0.786    0.1721    0.2160   0.09300
501    13.82    24.49    92.33   103.78  ...     0.786    0.1521    0.3651   0.11830
563    20.92    25.09   143.00   103.78  ...     0.786    0.2542    0.2929   0.09873

[5 rows x 32 columns]

In [21]:
treino_y.head()

114    B
457    B
269    B
520    B
38     M
Name: diagnostico, dtype: object

## Inicializando o método de _machine learning_

In [24]:
from sklearn.ensemble import RandomForestClassifier


classificador = RandomForestClassifier(n_estimators = 100)
classificador.fit(treino_x,treino_y)
print("Classificador random foreste inicializado e treinado")

RandomForestClassifier()

In [26]:
print("O resultado da classificação foi de %.2f%%" % (classificador.score(teste_x, teste_y)*100))

O resultado da classificação foi de 92.40%

## Inicializando o Classificador Dummy 
#### Parece ser uma prática comum a utilização do classificador dummy para comparar os resultados apresentados pelos métodos de _machine learning_

In [28]:
from sklearn.dummy import DummyClassifier

SEED = 123143
random.seed(SEED)

classificador_bobo = DummyClassifier(strategy = "most_frequent")
classificador_bobo.fit(treino_x, treino_y)

print("Resultado da classificação boba %.2f%%" %(classificador_bobo.score(teste_x, teste_y)*100))

Resultado da classificação boba 66.67%